function main()
	setGxtEntry("SPARROW", "T.A.R.D.I.S.")
	setGxtEntry("RHINO", "Dalek")
	setGxtEntry("RCCAM", "K-9")
	setGxtEntry("BUCCANE", "Impala 1967")
	setGxtEntry("PSY", "Seems that person has no imagination...")
	setGxtEntry("CHIC", "He ditched you...")
	setGxtEntry("CAMERAT", "Close-Up Camera Activated")
	setGxtEntry("CAMERAF", "Close-Up Camera Deactivated")
	setGxtEntry("UNLOCK", "The Car is Unlocked!")
	setGxtEntry("LOCK", "The Car is Locked!")
	setGxtEntry("LCK", "Lock the TARDIS")
	setGxtEntry("HADS", "H.A.D.S. Settings")
	setGxtEntry("TMMENU", "Control Panel")
	setGxtEntry("TDMENU", "System Interface")
	setGxtEntry("MANUAL", "Manual Teleport")
	setGxtEntry("RANDOM", "Random Teleport")
	setGxtEntry("PROGRAM", "Programming Teleport")
	setGxtEntry("TSHIFT", "Time Travel")
	setGxtEntry("VORTEX", "Vortex Flight")
	setGxtEntry("RNDFLT", "Random Flight")
	setGxtEntry("EXT", "Close Panel")
	setGxtEntry("FRETURN", "Fast Return")
	setGxtEntry("TLOCK", "M.D.L.M. Control")
	setGxtEntry("INVCON", "Cloaking System Control")
	setGxtEntry("SPSI", "Show System Interface")
	setGxtEntry("SYSR", "Display System Readouts")
	setGxtEntry("EXTI", "Close Interface")
	setGxtEntry("SHLD_S", "Shield")
	setGxtEntry("SHLD_S_R", "~r~Shield")
	setGxtEntry("SHLD_H", "Shell")
	setGxtEntry("SHLD_H_R", "~r~Shell")
	setGxtEntry("ENER_S", "Energy")
	setGxtEntry("ENER_SR", "~r~Energy")
	setGxtEntry("TUNLCK", "Doors unlocked")
	setGxtEntry("TLCK", "Doors locked")
	setGxtEntry("SHBAR", "H.U.D. Switch")
	setGxtEntry("CORD1", "tardismemorbank")
	setGxtEntry("CORD2", "tardismemorbank")
	setGxtEntry("CORD3", "tardismemorbank")
	setGxtEntry("CORD4", "tardismemorbank")
	setGxtEntry("CORD5", "tardismemorbank")
	setGxtEntry("CORD6", "tardismemorbank")
	setGxtEntry("CORD7", "tardismemorbank")
	setGxtEntry("CORD8", "tardismemorbank")
	setGxtEntry("CORD9", "tardismemorbank")
	setGxtEntry("CORD10", "tardismemorbank")
	setGxtEntry("SAVEC", "Save Current Coordinates")
	setGxtEntry("SAVEMES", "Select a Memory Bank to save")
	setGxtEntry("LOCLIST", "Location List")
	setGxtEntry("EXTL", "Close List")
	setGxtEntry("SREPT", "Self-Repair Trigger")
	setGxtEntry("SREPTEXT", "Self-Repair Activated~n~Leave the ship~n~To initiate")
	setGxtEntry("HADSED", "Enable/Disable HADS")
	setGxtEntry("HADSF", "HADS water switch")
	setGxtEntry("HADSW", "HADS fire switch")
	setGxtEntry("SPINS", "Spin settings")
	setGxtEntry("SPINM", "Press ~b~UP/DOWN ARROWS~w~ to increase/decrease spinning speed~n~~b~0~w~ to disable~n~~b~D~w~ to set default (40)~b~SPACE~w~ to apply settings~n~~n~Positive value - anti-clockiwise spinning~n~Negative - clockwise spinning")
	setGxtEntry("PREVH", "P for location preview~n~ENTER to exit")
	setGxtEntry("SONICT", "Thermal Scanning~n~Completed")
	setGxtEntry("SONICN", "Photon Scanning~n~Completed")
	setGxtEntry("k9aval", "K-9 AVAILABLE")
	setGxtEntry("k9lost", "Last position of K-9 is marked on the radar")
	setGxtEntry("k9bonl", "There you find the metal dog again xD")
	setGxtEntry("k9hcan", "K-9 got ur message and dematerialized away ;)")
	setGxtEntry("k9tout", "K-9 is pissed off about how you left him like that so he just go dematerialized :(")
	setGxtEntry("k9tcan", "K-9 TARGET CANCELLED")
	setGxtEntry("NOHUMAN", "Press E to switch characters")
	setGxtEntry("TARSAV", "Press E to save game")
	setGxtEntry("TARSIT", "Press E to sit down")
	setGxtEntry("TARSTA", "Press E to stand up")
	setGxtEntry("TARSIR", "Seriously?")
	setGxtEntry("FAILCL", "Function Failing: ~r~Cloaking is Enabled")
	setGxtEntry("HADSON", "H.A.D.S. ~g~Activated")
	setGxtEntry("HADSOF", "H.A.D.S. ~r~Deactivated")
	setGxtEntry("ENERLA", "~r~Initial Energy Lacking")
	setGxtEntry("CL_FIR", "Function Failing: ~r~Cloaking is Enabled")
	setGxtEntry("HS_FIR", "Function Failing: ~r~H.A.D.S. is Enabled")
	setGxtEntry("ENSUPD", "~r~Energy suplly is disabled!")
	setGxtEntry("SOLSYS", "Solar Sys, Sol-3")
	setGxtEntry("SLSYSF", "Solar system, Sol-3")
	setGxtEntry("UNKLOC", "Unknown")
	setGxtEntry("TIMESET", "Destination Time Set~n~Autopilot ~g~Enabled")
	setGxtEntry("FRTACT", "Fast Return ~g~Activated")
	setGxtEntry("STAT1", "In Vortex")
	setGxtEntry("STAT2", "IDLE")
	setGxtEntry("STAT3", "Materialising")
	setGxtEntry("STAT4", "Dematerialising")
	setGxtEntry("STAT5", "Triangulating")
	setGxtEntry("FAILCL", "Function Failing: ~r~Cloaking is Enabled")
	setGxtEntry("APDIS", "Autopilot ~r~Disabled")
	setGxtEntry("HADSON", "H.A.D.S. ~g~Activated")
	setGxtEntry("HADSOF", "H.A.D.S. ~r~Deactivated")
	setGxtEntry("ENERLA", "~r~Initial Energy Lacking")
	setGxtEntry("ENSUPD", "Function Failing: ~r~Energy Supply Disabled")
	setGxtEntry("SOLSYS", "Solar Sys, Sol-3")
	setGxtEntry("SLSYSF", "Solar system, Sol-3")
	setGxtEntry("UNKLOC", "Unknown")
	setGxtEntry("FRTACT", "Fast Return ~g~Activated")
	setGxtEntry("AFIRON", "Fire Reaction ~g~Enabled")
	setGxtEntry("AFIROF", "Fire Reaction ~r~Disabled")
	setGxtEntry("AWATON", "Water Reaction ~g~Enabled")
	setGxtEntry("AWATOF", "Water Reaction ~r~Disabled")
	setGxtEntry("PRGCAN", "Cancel")
	setGxtEntry("PRGSAV0", "Coordinates ~r~Unsaved")
	setGxtEntry("PRGSAV1", "Coordinates ~g~Saved")
	setGxtEntry("ALOCCLO", "Cloaking Energy ~g~Allocated")
	setGxtEntry("ALOCHAD", "H.A.D.S. Energy ~g~Allocated")
	setGxtEntry("REMECLO", "Cloaking Energy ~r~Released")
	setGxtEntry("REMEHAD", "H.A.D.S. Energy ~r~Released")
	setGxtEntry("SH_S", "Shield")
	setGxtEntry("SH_S_R", "~r~Shield")
	setGxtEntry("SH_H", "Shell")
	setGxtEntry("SH_H_R", "~r~Shell")
	setGxtEntry("SRNODAM", "No Critical Damage Detected")
	setGxtEntry("SRPTXT", "Self-Repair Activated~n~Leave the ship~n~To initiate")
	setGxtEntry("DRIFTD", "TARDIS just drifted because you didn't turn the Handbrake On")
	setGxtEntry("DRIFTF", "TARDIS Available~n~Use the Key if she is in a different Timeline")
	setGxtEntry("DRIFTT", "TARDIS new location marked on map by T")
	setGxtEntry("DRIFTM", "Use any Sonic Device to scan and locate the current position of TARDIS")
	setGxtEntry("BT1", "J;yп93:ЭэПUy")
	setGxtEntry("BT2", "9аНЮуxPЖ0Clzз.I[8")
	setGxtEntry("BT3", "Ы0(kOпlаЙ8N:")
	setGxtEntry("BT4", "c0SцД]бenТH_9")
	setGxtEntry("BT5", "U3i%?9zыЖХяG")
	setGxtEntry("BT6", "8ЁяЕ1RC7MЖvt%шd(")
	setGxtEntry("BT7", "JгЫMf%РC4№09hdФс")
	setGxtEntry("BT8", "tпJЮыaЧ7}0У,Xnщ")
	setGxtEntry("BT9", "dг0Ч=Pb4DЗ")
	setGxtEntry("BT10", "Од6f&Ez")
	setGxtEntry("BT11", "Nехs2Ъn$Г")
	setGxtEntry("BT12", "рF[1гtЯp]АДbT9R0")
	setGxtEntry("BT13", "{Э5xлTHё4zc)Л")
	setGxtEntry("BT14", "ФЬ;lУASв0c$tю63O")
	setGxtEntry("BT15", "ЛgАуwwW4(&9шщH")
	setGxtEntry("HPRTXT", "Hold F12 for the console helper")
	setGxtEntry("BFLAIR", "Function Failing: ~r~TARDIS Not Landed")
	setGxtEntry("VRTREV", "Vortex ~g~Reversed")
	setGxtEntry("REGEN1", "The Timelord is dead")
	setGxtEntry("REGEN2", "Press Y to Regenerate~n~Press R to hold Regeneration")
	setGxtEntry("REGEN3", "Tap R rapidly to hold Regeneration Longer or Press Y to Regenerate Now")
	setGxtEntry("TUTABLE", "Press E to check")
	setGxtEntry("TUTON", "Tutorial Hints ~g~Enabled")
	setGxtEntry("TUTOFF", "Tutorial Hints ~r~Disabled")
	setGxtEntry("TUTSONI", "1 - Thermal Scan~n~2 - (Un)Lock~n~3 - Photon Scan~n~U - Explode Vehicles~n~H - Deflate Tires~n~J - Accelerate Vehicles~n~K - Break Engine~n~RMB+Above Keys - Long Range Mode")
	setGxtEntry("TUTSON2", "RMB+Z - Disarm Mode~n~Sonic Screwdrivers~n~(exclude Shades and Disarm Mode)~n~can also be activated while holding Nothing")
	setGxtEntry("TUTAR", "Z - Handbrake~n~X - Fast Landing~n~T - Throttle~n~C - Cloak Switcher~n~LMB - Accelerate")
	setGxtEntry("TUTVOR", "LMB - Reverse Vortex~n~Z - Exit Vortex")
	setGxtEntry("TUTPSY", "Press 2 to target any pedestrian to be your New Companion")
	setGxtEntry("TUTGAY9", "RMB+R - Select Target~n~4 - Cancel Target~n~9 - Leave")
	setGxtEntry("ANGELIT", "Time Left")
end
